config/routes.rb
Rails.application.routes.draw do
  get '/' => 'application#layout'
  get 'shared/nav'

  get 'search/index'

  get 'contacts' => "contacts#index"

  get 'search' => "articles#search"

  resources :articles

  get 'home' => 'home#index'

  get 'user/info' => 'application#user_info'

  devise_for :users

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	validates :description, length: { in: 3..10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :articles
   mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def layout
    render file: 'layouts/application'
  end

  def user_info
    render text: current_user.to_json(only: [:name, :age, :phone, :website, :adress, :email])
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :avatar, :age, :website, :phone, :adress, :current_password) }
  end
  protect_from_forgery with: :exception
  layout :false
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render text: {msg: "Статья успешно создана!"}.to_json }
      else
        format.html { render :new }
        format.json { render text: {msg: "Ошибка!", errors: @article.errors}.to_json, status: 500 }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render text: {msg: "Ошибка!", errors: @article.errors}.to_json, status: 500 }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { render text: Article.all.to_json }
    end
  end
  def search
    q = params[:q]
    if q && q.length !=0
      render text: Article.where('(title LIKE ?) OR (description LIKE ?)', "%#{q}%", "%#{q}%").to_json
    else
      render text: Article.all.to_json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def nav
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  .field.title
    = f.label :title
    = f.text_field :title, "ng-model" => "formData.article['title']", "ng-init"=>"formData.article['title']='#{@article.title}'"
  .field.description
    = f.label :description
    = f.text_area :description, "ng-model" => "formData.article['description']", "ng-init"=>"formData.article['description']='#{@article.description}'"
  a.btn.btn-success ng-click="saveArticle(formData)" Сохранить

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles
form.navbar-form.navbar-right role="search"  action="search"
  .form-group
    input.form-control placeholder="Search" type="text" ng-model="$root.search"
table.table.table-bordered.table-hover
  thead
    tr
      th Title 
      th Description
      th
      th
      th

  tbody 
    tr ng-repeat="article in articles"
      td 
        | {{article.title}}
      td 
        | {{article.description}}
      td.w0
        a href="/#/articles/{{article.id}}" Смотреть
      td.w0
        a href="/#/articles/{{article.id}}/edit" Редактировать
      td.w0
        a href="" ng-click="remove(article.id)" Удалить 

br

a href="/#/articles/new" Создать статью

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p#notice = notice

p
  strong Title:
  = @article.title
p
  strong Description:
  = @article.description

app/views/contacts/index.html.slim
h1 Contacts#index
p Find me in app/views/contacts/index.html.slim

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim
/ = link_to 'Article', article_path, :method => :get

app/views/layouts/application.html.slim
html ng-app="resourses"
head
  title Resourses
  = stylesheet_link_tag    'application', media: 'all'
  script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"
  = javascript_include_tag 'application'
  = csrf_meta_tags 
body
  ng-include src="'/shared/nav'"
  .wrap
    ng-view

app/views/search/index.html.slim
h1 Search#index
p Find me in app/views/search/index.html.slim

app/views/shared/nav.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Логотип
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li  ng-class="{active: $root.currentPage=='home'}"
          a href="/#/" Главная страница
        li ng-class="{active: $root.currentPage=='articles'}"
          a href="/#/articles"  Статьи
        li  ng-class="{active: $root.currentPage=='contacts'}"
          a href="/#/contacts"  Контакты
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to '/#'+edit_user_registration_path do
              =image_tag current_user.avatar, class: "img_size"
          li
            - if current_user.name
              =link_to current_user.name, '/#'+edit_user_registration_path
            - else 
              =link_to current_user.email, '/#'+edit_user_registration_path
          li
            = link_to 'Выход', destroy_user_session_path, :method => "delete"
        -else
          li
            =link_to 'Вход', user_session_path
    /! /.navbar-collapse
  /! /.container-fluid